import type { VercelRequest, VercelResponse } from '@vercel/node';
import { supabase } from '../_supabaseClient.js';
import { createSupabaseAuthSession } from '../_authHelper.js';

/**
 * POST /api/auth/exchange-code
 * 
 * Exchanges a short-lived, single-use code for real Supabase Auth tokens.
 * The code is generated by the Telegram bot after verification and stored
 * in the database with a 5-minute TTL.
 * 
 * Body: { code: string }
 * Response: { access_token, refresh_token, userId, onboarding, cards, transactions }
 */
export default async function handler(req: VercelRequest, res: VercelResponse) {
  res.setHeader('Access-Control-Allow-Credentials', 'true');
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET,OPTIONS,POST');
  res.setHeader('Access-Control-Allow-Headers', 'X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version');

  if (req.method === 'OPTIONS') {
    return res.status(200).end();
  }

  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method Not Allowed' });
  }

  try {
    const { code } = req.body || {};
    if (!code || typeof code !== 'string' || code.length < 16) {
      return res.status(400).json({ error: 'Missing or invalid code' });
    }

    // 1. Look up the exchange code in the database
    const codeId = `exchange_${code}`;
    const { data: codeDoc, error: lookupError } = await supabase
      .from('users')
      .select('*')
      .eq('id', codeId)
      .maybeSingle();

    if (lookupError || !codeDoc) {
      return res.status(400).json({ error: 'Invalid or expired code' });
    }

    // 2. Check expiry (5-minute TTL)
    if (codeDoc.session_expires_at && new Date(codeDoc.session_expires_at).getTime() < Date.now()) {
      // Delete expired code
      await supabase.from('users').delete().eq('id', codeId);
      return res.status(400).json({ error: 'Code expired' });
    }

    // 3. Check if code was already used
    if (codeDoc.login_request_status === 'USED') {
      return res.status(400).json({ error: 'Code already used' });
    }

    const tgId = codeDoc.telegram_id;
    if (!tgId) {
      return res.status(400).json({ error: 'Invalid code: no telegram_id' });
    }

    // 4. Mark code as used immediately (single-use)
    await supabase.from('users').update({
      login_request_status: 'USED',
      updated_at: new Date().toISOString()
    }).eq('id', codeId);

    // 5. Get the real user document
    const userId = `moliya_user_tg_${tgId}`;
    const { data: userDoc } = await supabase
      .from('users')
      .select('*')
      .eq('id', userId)
      .maybeSingle();

    // 6. Create real Supabase Auth session
    const authSession = await createSupabaseAuthSession(
      String(tgId),
      { name: userDoc?.name || '', telegram: userDoc?.telegram || '' }
    );

    if (!authSession) {
      return res.status(500).json({ error: 'Failed to create auth session' });
    }

    // 7. Return tokens + user data
    return res.status(200).json({
      access_token: authSession.access_token,
      refresh_token: authSession.refresh_token,
      userId,
      sessionToken: userDoc?.session_token || codeDoc.session_token || null,
      onboarding: userDoc?.onboarding || null,
      cards: userDoc?.cards || [],
      transactions: userDoc?.transactions || [],
      isPremium: userDoc?.is_premium || false
    });
  } catch (error: any) {
    console.error('[EXCHANGE-CODE] Error:', error);
    return res.status(500).json({ error: error.message });
  }
}
